### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#16]
@gehalber Beginning work on the form...

http://bksh.etc-nyc.com/apply/

More to do.

**Comment by halfempty** [comment]
@gehalber Okay, I think this formatting is complete...

http://bksh.etc-nyc.com/apply/

Please re-open if not.

**Comment by gehalber** [comment]
Can you add this text to the top?

We are looking forward to hearing from you. This year we will be conducting in-person meetings with interested families in lieu of a lengthy written application. Please submit the form below so that we may schedule a time to discuss your interest in Brooklyn Schoolhouse and learn more about your child. We admit children for all programs on a rolling basis, and once we reach capacity we maintain a waiting list.

**Comment by gehalber** [comment]
The form looks really good, but could tweak the form slightly?

Row 1: First name (cell 1)  /  Last name (cell 2)
Row 2: Phone Number (cell 1) /  email  (cell 2)
Row 3: Child's First name  (cell 1)  /  Child's Last name  (cell 2)
Row 4: Child's Birthday   (cell 1)  /  Which program are you interested in?  (cell 2)
Row 5: Please leave a message if you wish...

**Comment by gehalber** [comment]
Also add shadow to the apply button

**Comment by halfempty** [comment]
@gehalber okay done
